[package]
name = "jsoncan_rust"
version = "0.1.1"
edition = "2024"
default-run = "jsoncan_rust"

[[bin]]
name = "busload"

[[bin]]
name = "cppcodegen"

[lib]
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
rusqlite = { version = "0.38.0", features = ["bundled"] }
r2d2 = "0.8.10"
r2d2_sqlite = "0.32"
askama = "0.15.1"
convert_case = "0.10.0"
