[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
serialport = "4.0"
ctrlc = "3.5"
tokio = { version = "1", features = ["full"] }
tokio-serial = "5"
influxdb2 = "0.5"
dotenv = "0.15"